// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6YWbAhS5tQQRFkLE21F4kw
// Component: kMmJWCRMpfj
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_myna_dapp.module.css"; // plasmic-import: 6YWbAhS5tQQRFkLE21F4kw/projectcss
import * as sty from "./PlasmicButton2.module.css"; // plasmic-import: kMmJWCRMpfj/css

export type PlasmicButton2__VariantMembers = {
  color: "primary" | "secondary" | "offwhite" | "transparent";
};

export type PlasmicButton2__VariantsArgs = {
  color?: SingleChoiceArg<"primary" | "secondary" | "offwhite" | "transparent">;
};

type VariantPropType = keyof PlasmicButton2__VariantsArgs;
export const PlasmicButton2__VariantProps = new Array<VariantPropType>("color");

export type PlasmicButton2__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicButton2__ArgsType;
export const PlasmicButton2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicButton2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultButton2Props {
  children?: React.ReactNode;
  color?: SingleChoiceArg<"primary" | "secondary" | "offwhite" | "transparent">;
  className?: string;
}

function PlasmicButton2__RenderFunc(props: {
  variants: PlasmicButton2__VariantsArgs;
  args: PlasmicButton2__ArgsType;
  overrides: PlasmicButton2__OverridesType;
  dataFetches?: PlasmicButton2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox___8H42J)}>
        <div
          className={classNames(defaultcss.all, sty.freeBox__o0E7U, {
            [sty.freeBox__color_offwhite__o0E7UDq6R1]: hasVariant(
              variants,
              "color",
              "offwhite"
            ),
            [sty.freeBox__color_secondary__o0E7UW6Dor]: hasVariant(
              variants,
              "color",
              "secondary"
            ),
            [sty.freeBox__color_transparent__o0E7UTr011]: hasVariant(
              variants,
              "color",
              "transparent"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Button Label",
            value: args.children,
            className: classNames(sty.slotChildren, {
              [sty.slotChildren__color_offwhite]: hasVariant(
                variants,
                "color",
                "offwhite"
              ),
              [sty.slotChildren__color_secondary]: hasVariant(
                variants,
                "color",
                "secondary"
              ),
              [sty.slotChildren__color_transparent]: hasVariant(
                variants,
                "color",
                "transparent"
              )
            })
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButton2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButton2__VariantsArgs;
    args?: PlasmicButton2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicButton2__Fetches;
  } & Omit<PlasmicButton2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButton2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButton2__ArgProps,
      internalVariantPropNames: PlasmicButton2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicButton2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton2";
  } else {
    func.displayName = `PlasmicButton2.${nodeName}`;
  }
  return func;
}

export const PlasmicButton2 = Object.assign(
  // Top-level PlasmicButton2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicButton2
    internalVariantProps: PlasmicButton2__VariantProps,
    internalArgProps: PlasmicButton2__ArgProps
  }
);

export default PlasmicButton2;
/* prettier-ignore-end */
